### ISSUE TITLE
Question: Official CircuitPython Support for VL53L4CX

### ISSUE THREAD

**Issue by ScottMonaghan** [caternuson/Adafruit_CircuitPython_VL53L4CX#1]
Hello,

Is this planned as the official CircuitPython support for the VL53L4CX?
If so is there a ballpark timeline for completion?

I'd like to integrate the VL53L4CX into my project, and I use all python/CircuitPython libraries, and I'd like to keep my project consistent if this is expected in the near-term.

Thanks!

**Comment by caternuson** [comment]
It's an attempt at it. There's a lot more going on with the VL53L4CX compared to the VL53L4CD. So the conversion from the [Arduino library](https://github.com/stm32duino/VL53L4CX) is not as easy.

`If so is there a ballpark timeline for completion?`
There is not. Just working on this as time allows.

**Comment by ScottMonaghan** [comment]
Thank you for the reply!
